### ISSUE TITLE
Erro no uso: def box(height:, pad:5, &block)

### ISSUE THREAD

**Issue by smorigo** [asseinfo/br_danfe#12]
Boa noite pessoal tudo bem?
Instalei a gem em um projeto e estou recebendo esse erro: 

Warning: You're using Rubygems 2.0.14.1 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': /Library/Ruby/Gems/2.0.0/gems/br_danfe-0.5.2/lib/br_danfe/cce_lib/document.rb:21: syntax error, unexpected ',' (SyntaxError)
      def box(height:, pad:5, &block)
                      ^
/Library/Ruby/Gems/2.0.0/gems/br_danfe-0.5.2/lib/br_danfe/cce_lib/document.rb:44: syntax error, unexpected keyword_end, expecting end-of-input

**Comment by linielson** [comment]
Para utilizar o required named parameter você precisará utilizar o ruby 2.1.0

http://stackoverflow.com/a/19309645
https://robots.thoughtbot.com/ruby-2-keyword-arguments

**Comment by smorigo** [comment]
Atualizei o ruby e funcionou perfeitamente 👍
