### ISSUE TITLE
Logo no Danfe

### ISSUE THREAD

**Issue by smorigo** [asseinfo/br_danfe#13]
Olá pessoal tudo bem?
Estou tentando adicionar o logo na geração do DANFE mas o mesmo não aparece, já identificaram esse problema? 

order = Order.find(params[:id])
danfe = BrDanfe::Danfe.new(order.xml)

danfe.options.logo_path = "#{Rails.public_path}/logo-danfe.png"

send_data danfe.render_pdf, filename: "DANFE_#{order.id}.pdf", type: "application/pdf"

O DANFE está sendo gerado com sucesso, mas o logo não é apresentado.

**Comment by linielson** [comment]
Olá Rafael, não tivemos nenhum problema desse tipo, e seu código parece estar correto.
Você está utilizando qual versão da gem?
Na versão mais recente 0.5.2, renomeamos ```logo_path``` para ```logo```
```
danfe.options.logo = "spec/fixtures/logo.png
```

Nesta nova versão também adicionamos mais uma propriedade ```logo_dimensions```, para redimensionar corretamente  o logo:
```
danfe.options.logo_dimensions = { width: largura_do_logo, height: altura_do_logo }
```
