### ISSUE TITLE
Borda da tabela de produtos

### ISSUE THREAD

**Issue by linielson** [asseinfo/br_danfe#18]
Ajustar a borda da tabela de produtos. Está mais grossa.

**Comment by kaynanguarany** [comment]
```
def render_table(data, start_position, height)
  @pdf.y = start_position
  @pdf.bounding_box [0.75.cm, @pdf.cursor], width: 19.56.cm, height: height do
    @pdf.table data.map{ |item| [item] }, { header: true }
  end
end
```

Acredito que o método ``` table``` chamado sem as opções de ``` cell_style ``` sobrescreve os valores previamente definidos na chamado do método ```make_table``` na classe [https://github.com/asseinfo/br_danfe/blob/master/lib/br_danfe/danfe_lib/det_body.rb](url) 

@marcosdemelo gostaria que eu enviasse um PR com o ajuste?

**Comment by marcosdemelo** [comment]
@kaynanguarany seria muito legal, obrigado!

**Comment by linielson** [comment]
Resolved on #38
